# -*- coding: utf-8 -*-
"""Sentiment Analysis of Restaurant Reviews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v3zQWSOj1jUPmuUXDuvdmAWW1O6Vq13u

# **Sentiment Analysis of Restaurant Reviews**

# Import Dependentias
"""

import numpy as np
import pandas as pd

import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

import sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

"""#  Get Sms Dataset and Data preparation"""

df = pd.read_csv('Restaurant_Reviews.tsv', delimiter='\t', quoting=3)
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)

df.head()

df.tail()

df.shape

df['Liked'].value_counts()

"""# Data cleaning"""

corpus = []
ps = PorterStemmer()

for i in range(0,df.shape[0]):
    message = re.sub(pattern='[^a-zA-Z]', repl=' ', string=df.Review[i])
    message = message.lower()
    words = message.split()
    words = [word for word in words if word not in set(stopwords.words('english'))]
    words = [ps.stem(word) for word in words]
    message = ' '.join(words)
    corpus.append(message)

corpus[0:10]

"""# Feature extraction"""

cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()
y = df.iloc[:, 1].values

"""# Model training"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

best_accuracy = 0.0
alpha_val = 0.0
for i in np.arange(0.0,1.1,0.1):
    temp_classifier = MultinomialNB(alpha=i)
    temp_classifier.fit(X_train, y_train)
    temp_y_pred = temp_classifier.predict(X_test)
    score = accuracy_score(y_test, temp_y_pred)
    print("Accuracy score for alpha={} is: {}%".format(round(i,1), round(score*100,2)))
    if score>best_accuracy:
        best_accuracy = score
        alpha_val = i
print('--------------------------------------------')
print('The best accuracy is {}% with alpha value as {}'.format(round(best_accuracy*100, 2), round(alpha_val,1)))

classifier = MultinomialNB(alpha=0.1)
classifier.fit(X_train, y_train)

"""# Model *evaluation*"""

y_pred = classifier.predict(X_test)

y_pred

acc_s = accuracy_score(y_test, y_pred)*100

print("Accuracy Score {} %".format(round(acc_s,2)))

"""# PLOTTING THE CONFUSION MATRIX"""

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

plt.figure(figsize=(10, 6))
sns.heatmap(cm, annot=True, cmap="viridis", xticklabels=['Negative', 'Positive'], yticklabels=['Negative', 'Positive'])
plt.xlabel('Predicted values')
plt.ylabel('Actual values')
plt.show()  # Display the heatmap

"""# Prediction function"""

def predict_review(sample_message):
    sample_message = re.sub(pattern='[^a-zA-Z]',repl=' ', string = sample_message)
    sample_message = sample_message.lower()
    sample_message_words = sample_message.split()
    sample_message_words = [word for word in sample_message_words if not word in set(stopwords.words('english'))]
    ps = PorterStemmer()
    final_message = [ps.stem(word) for word in sample_message_words]
    final_message = ' '.join(final_message)
    temp = cv.transform([final_message]).toarray()
    return classifier.predict(temp)

"""# Result"""

result = ['Ohhh Shit! Negetive Review','Good! Positive Review']

msg = 'The food is really good here.'

if predict_review(msg):
    print(result[1])
else:
    print(result[0])

msg = 'Food was pretty bad and the service was very slow.'

if predict_review(msg):
    print(result[1])
else:
    print(result[0])

msg = 'The food was absolutely wonderful, from preparation to presentation, very pleasing.'

if predict_review(msg):
    print(result[1])
else:
    print(result[0])